export const sampleData = {
  personalInfo: {
    firstName: "John",
    lastName: "Doe",
    email: "johndoe@example.com",
    phoneNumber: "1234567890",
    gender: "Male",
    dateOfBirth: new Date("1990-01-01"),
    currentAddress: "123 Main Street",
    permanentAddress: "456 Elm Street",
    photo: "https://example.com/photo.jpg",
  },
  education: {
    universities: [
      {
        type: "UG",
        university: "University 1",
        certificate: "Certificate 1",
      },
      {
        type: "PG",
        university: "University 2",
        certificate: "Certificate 2",
      },
    ],
    portfolioURL: "https://example.com/portfolio",
  },
  experience: {
    hasExperience: true,
    experiences: [
      {
        appointmentOrder: "Appointment 1",
        experienceCertificate: "Certificate 1",
        joiningDate: new Date("2010-01-01"),
        leavingDate: new Date("2015-12-31"),
        experience: "Experience 1",
      },
      {
        appointmentOrder: "Appointment 2",
        experienceCertificate: "Certificate 2",
        joiningDate: new Date("2016-01-01"),
        leavingDate: new Date("2020-12-31"),
        experience: "Experience 2",
      },
    ],
  },
  designation: {
    designation: "Professor",
    academicYear: 2023,
    semester: "Spring",
    courseTeaching: {
      theory: "Theory Course",
      laboratory: "Lab Course",
    },
    additionalResponsibilities: {
      order: 1,
      details: "Additional Responsibilities Details",
    },
  },
  facultyPublication: [
    {
      booksPublished: 5,
      chaptersPublishedAndReferences: 10,
      internationalJournals: 3,
      nationalJournals: 2,
      internationalConferences: 4,
      nationalConferences: 3,
      patents: 1,
    },
  ],
  researchProjects: [
    {
      name: "Research Project 1",
      fundingAgency: "Agency 1",
      type: "Type 1",
      year: 2022,
      duration: 2,
      fundsProvided: 50000,
      relevantDocuments: "https://example.com/project1-docs",
      details: "Research Project 1 Details",
    },
    {
      name: "Research Project 2",
      fundingAgency: "Agency 2",
      type: "Type 2",
      year: 2021,
      duration: 3,
      fundsProvided: 75000,
      relevantDocuments: "https://example.com/project2-docs",
      details: "Research Project 2 Details",
    },
  ],
  awardsRecognition: [
    {
      name: "Award 1",
      receivedFrom: "Organization 1",
      recognizedUnder: "Category 1",
      level: "National",
      year: 2020,
      incentivesReceived: "Incentives 1",
      relevantDocuments: "https://example.com/award1-docs",
      details: "Award 1 Details",
    },
    {
      name: "Award 2",
      receivedFrom: "Organization 2",
      recognizedUnder: "Category 2",
      level: "International",
      year: 2019,
      incentivesReceived: "Incentives 2",
      relevantDocuments: "https://example.com/award2-docs",
      details: "Award 2 Details",
    },
  ],
  eContent: {
    title: "E-Content 1",
    domain: "Domain 1",
    developedFor: "Organization 1",
    uploadedDate: new Date("2023-05-01"),
    duration: 60,
    relevantDocumentsUsed: "https://example.com/econtent1-docs",
    link: "https://example.com/econtent1",
  },
};
